/* CATEGORIES ACTION TYPES */
export const CATEGORIES = {
    LOAD_ALL: 'LOAD_CATEGORIES'
}

/* POSTS ACTION TYPES */
export const POSTS = {
    LOAD_ALL: 'LOAD_POSTS',
    LOAD_DETAIL: 'LOAD_POST_DETAIL',
    UPDATE: 'UPDATE_POST',
    DELETE: 'DELETE_POST'
}

/* COMMENTS ACTION TYPES */
export const COMMENTS = {
    LOAD_ALL: 'LOAD_COMMENTS',
    LOAD_DETAIL: 'LOAD_COMMENT_DETAIL',
    UPDATE: 'UPDATE_COMMENT',
    DELETE: 'DELETE_COMMENT'
}