/* CATEGORIES ACTION TYPES */
export const CATEGORIES = {
    LOAD_ALL: 'LOAD_CATEGORIES'
}

/* POSTS ACTION TYPES */
export const POSTS = {
    LOAD_ALL: 'LOAD_POSTS',
    LOAD_DETAIL: 'LOAD_POST_DETAIL'
}